Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1
  Port: 3307
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30